# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.srcs/sources_1/bd/TopLevel/ip/TopLevel_mdm_1_0/TopLevel_mdm_1_0.xci
# IP: The module: 'TopLevel_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_mdm_1_0/TopLevel_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_mdm_1_0/TopLevel_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.srcs/sources_1/bd/TopLevel/ip/TopLevel_mdm_1_0/TopLevel_mdm_1_0.xci
# IP: The module: 'TopLevel_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_mdm_1_0/TopLevel_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_mdm_1_0/TopLevel_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
