# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.srcs/sources_1/bd/TopLevel/ip/TopLevel_clk_wiz_0_0/TopLevel_clk_wiz_0_0.xci
# IP: The module: 'TopLevel_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_clk_wiz_0_0/TopLevel_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_clk_wiz_0_0/TopLevel_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_clk_wiz_0_0/TopLevel_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.srcs/sources_1/bd/TopLevel/ip/TopLevel_clk_wiz_0_0/TopLevel_clk_wiz_0_0.xci
# IP: The module: 'TopLevel_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_clk_wiz_0_0/TopLevel_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_clk_wiz_0_0/TopLevel_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/pr3de/Documents/MASA/ECE475Project/ECE475Project.gen/sources_1/bd/TopLevel/ip/TopLevel_clk_wiz_0_0/TopLevel_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevel_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
